# Generated by Django 4.1 on 2022-11-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logos', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'BrandLogo',
                'verbose_name_plural': 'BrandLogos',
            },
        ),
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='src/static/index-images')),
                ('gender', models.BooleanField(default=False, null=True)),
                ('text', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'SliderImage',
                'verbose_name_plural': 'SliderImages',
            },
        ),
    ]
