# Generated by Django 4.1 on 2022-11-26 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image.Product')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=30)),
                ('town_en', models.CharField(max_length=30, null=True)),
                ('town_ru', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30)),
                ('state_en', models.CharField(max_length=30, null=True)),
                ('state_ru', models.CharField(max_length=30, null=True)),
                ('postal_code', models.CharField(max_length=30)),
                ('shipping', models.CharField(max_length=30)),
                ('payment', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Checkout',
                'verbose_name_plural': 'Checkout',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('rating', models.FloatField()),
                ('followers', models.IntegerField()),
                ('reviews', models.TextField()),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vendor_Profile',
                'verbose_name_plural': 'Vendor_Profile',
            },
        ),
    ]
