# Generated by Django 4.1 on 2022-11-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='state_en',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='state_ru',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='town_en',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='town_ru',
        ),
        migrations.RemoveField(
            model_name='vendor_profile',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='vendor_profile',
            name='description_ru',
        ),
    ]
