# Generated by Django 4.1 on 2022-11-26 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_brand_brand_en_remove_brand_brand_ru_and_more'),
        ('order', '0003_remove_checkout_state_en_remove_checkout_state_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment',
            field=models.CharField(choices=[(1, 'Check Payment'), (2, 'Cash On Delivery'), (3, 'PayPal')], default=1, max_length=30),
        ),
    ]
