# Generated by Django 4.1 on 2022-11-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='flat_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='flat_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region_ru',
        ),
    ]
