# Generated by Django 4.1 on 2022-11-26 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('brand_en', models.CharField(max_length=30, null=True)),
                ('brand_ru', models.CharField(max_length=30, null=True)),
                ('brand_logo', models.ImageField(null=True, upload_to='src/static/brand_logos')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('category_en', models.CharField(max_length=30, null=True)),
                ('category_ru', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, unique=True)),
                ('color_en', models.CharField(max_length=30, null=True, unique=True)),
                ('color_ru', models.CharField(max_length=30, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=30)),
                ('name_en', models.CharField(default='name', max_length=30, null=True)),
                ('name_ru', models.CharField(default='name', max_length=30, null=True)),
                ('price', models.FloatField(null=True)),
                ('discount_percent', models.IntegerField(default=55)),
                ('title', models.CharField(max_length=50, null=True)),
                ('title_en', models.CharField(max_length=50, null=True)),
                ('title_ru', models.CharField(max_length=50, null=True)),
                ('availablity', models.BooleanField(null=True)),
                ('rating', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('description', models.TextField(default='This is the desciption of this item')),
                ('description_en', models.TextField(default='This is the desciption of this item', null=True)),
                ('description_ru', models.TextField(default='This is the desciption of this item', null=True)),
                ('fabric', models.CharField(default='silk', max_length=30)),
                ('fabric_en', models.CharField(default='silk', max_length=30, null=True)),
                ('fabric_ru', models.CharField(default='silk', max_length=30, null=True)),
                ('material', models.CharField(max_length=30, null=True)),
                ('material_en', models.CharField(max_length=30, null=True)),
                ('material_ru', models.CharField(max_length=30, null=True)),
                ('video', models.FileField(null=True, upload_to='src/static/product_videos')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('brand', models.ManyToManyField(to='product.brand')),
                ('category', models.ManyToManyField(to='product.category')),
                ('color', models.ManyToManyField(to='product.color')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='L', max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='WriteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30, null=True)),
                ('name_ru', models.CharField(max_length=30, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('review_title', models.CharField(max_length=50)),
                ('review_title_en', models.CharField(max_length=50, null=True)),
                ('review_title_ru', models.CharField(max_length=50, null=True)),
                ('review_desc', models.TextField(max_length=300)),
                ('review_desc_en', models.TextField(max_length=300, null=True)),
                ('review_desc_ru', models.TextField(max_length=300, null=True)),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'WriteReview',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('enddate', models.DateField()),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='product.size'),
        ),
        migrations.CreateModel(
            name='P_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='image', max_length=30)),
                ('image_name_en', models.CharField(default='image', max_length=30, null=True)),
                ('image_name_ru', models.CharField(default='image', max_length=30, null=True)),
                ('image', models.ImageField(upload_to='src/static/product_images')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='product.product')),
            ],
            options={
                'verbose_name': 'P_Image',
                'verbose_name_plural': 'P_Images',
            },
        ),
    ]
