# Generated by Django 4.1 on 2022-11-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='color',
            name='color_en',
        ),
        migrations.RemoveField(
            model_name='color',
            name='color_ru',
        ),
        migrations.RemoveField(
            model_name='p_image',
            name='image_name_en',
        ),
        migrations.RemoveField(
            model_name='p_image',
            name='image_name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabric_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabric_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='writereview',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='writereview',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='writereview',
            name='review_desc_en',
        ),
        migrations.RemoveField(
            model_name='writereview',
            name='review_desc_ru',
        ),
        migrations.RemoveField(
            model_name='writereview',
            name='review_title_en',
        ),
        migrations.RemoveField(
            model_name='writereview',
            name='review_title_ru',
        ),
    ]
